name: Suggest a new interview question
description: Propose an original question for the bank.
title: "[New Question]: "
labels: ["new-question"]
body:
  - type: markdown
    attributes:
      value: |
        Submit only original writing. Do not paste or lightly paraphrase copyrighted material.
  - type: input
    id: title
    attributes:
      label: Question title
      placeholder: "How would you ..."
    validations:
      required: true
  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      options:
        - Easy
        - Medium
        - Hard
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags
      placeholder: "rag,evaluation,debugging"
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Question text (1–5 sentences)
    validations:
      required: true
  - type: textarea
    id: strong
    attributes:
      label: What a strong answer includes
      description: At least 3 bullets.
      placeholder: |
        - ...
        - ...
        - ...
    validations:
      required: true
  - type: textarea
    id: pitfalls
    attributes:
      label: Common pitfalls
      description: At least 2 bullets.
      placeholder: |
        - ...
        - ...
    validations:
      required: true
  - type: checkboxes
    id: originality
    attributes:
      label: Originality confirmation
      options:
        - label: I confirm this proposal is written in my own words and does not copy copyrighted material.
          required: true
